### ISSUE TITLE
Turn off Table Stripe

### ISSUE THREAD

**Issue by jeffhoang** [maxazan/jquery-treegrid#20]
For a table with "table-striped", is it possible to turn off the table stripe for each child  and its children row?  Only allow stripes for the 1st level parent rows.

**Comment by YMA-MDL** [comment]
I guess you could do it yourself. having a special class 'SPECIALCLASS' on 1st level parent and applying some  css like 
```css
tr.SPECIALCLASS:nth-child(odd){
background-color: #XXX;
}
```
